name: Génération JSON PDF

on:
  push:
    paths:
      - '**.pdf'
      - 'scripts/generate_json.py'
      - '.github/workflows/generate-json.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Générer les fichiers JSON
        run: python scripts/generate_json.py

      - name: Commit et Push des JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add json/*.json
          git commit -m "Mise à jour automatique des JSON" || echo "Pas de changement"
          git push